### ISSUE TITLE
Implement doWork for TemperatureSensor

### ISSUE THREAD

**Issue by kyleoliveira** [Ohmbrewer/rhizome#7]
Get the doWork method in TemperatureSensor reading from the OneWire temperature probe. If all goes well, the reported temperature value on the Rhizome display should show the current temperature reading.

**Comment by azyth** [comment]
@kyleoliveira A few issues/questions that I cannot find the answer to in the class structure:
1. We need to set the PIN that the protocol reads from  with a ow_setPin(PIN#) call. when does this happen ?  or do we assume it will always be D0? and proceed in do_work as though it has happened?
2. do_work is where the actual code for reading in temp values actually occurs, however it returns the time it took to compute this? does it then simply call Temperature.h::from_C/F() to keep track of the temp internally? 
3. (thinking forward here) is each temperature.h instance its own object so that if we have more then one probe hooked up we would call it on each one individually? thereby needing to filter the UID of each probe and assocate it with the object of choice, aka "mash tun" or "rims tube", thereby calling mashtun::from_C inside the given do_work, which would need to know which equipment it was doing work on.  (is there a call parent functionality in here?)

**Comment by kyleoliveira** [comment]
> 1 . We need to set the PIN that the protocol reads from with a ow_setPin(PIN#) call. when does this happen ? or do we assume it will always be D0? and proceed in do_work as though it has happened?

I would expect that to happen in the constructor, unless it's impossible to do so for some reason. The pin would be the one provided by _pins/whichPins(). You may need to do something to ensure there is only one pin in that list, and it may be useful to wire a whichPin() method that always returns the front of the deque.

> 2 . do_work is where the actual code for reading in temp values actually occurs, however it returns the time it took to compute this? does it then simply call Temperature.h::from_C/F() to keep track of the temp internally? 

The most recent reading is stored in _lastReading. doWork() should update that value, probably using fromC().
The time thing isn't super useful, admittedly, but a lot of particle examples did that. We may consider changing that to an integer error code or something.

> 3 . (thinking forward here) is each temperature.h instance its own object so that if we have more then one probe hooked up we would call it on each one individually? thereby needing to filter the UID of each probe and assocate it with the object of choice, aka "mash tun" or "rims tube", thereby calling mashtun::from_C inside the given do_work, which would need to know which equipment it was doing work on. (is there a call parent functionality in here?)

Yes, if you check out the header for TemperatureSensor, _lastReading is a Temperature pointer. It gets initialized in the constructor and deleted in the destructor. Each object has it's own pointer that points to it's own internal (_lastReading) Temperature object. If you want info from a TemperatureSensor, simply use it's appropriate getter functions.

**Comment by kyleoliveira** [comment]
Putting a hold label on this until we get #17 sorted out.

**Comment by kyleoliveira** [comment]
Resolved by #24
