### ISSUE TITLE
Implement doWork for Relay and its subclasses

### ISSUE THREAD

**Issue by kyleoliveira** [Ohmbrewer/rhizome#8]
This shouldn't be too hard... I'm not even sure there's anything to do other than have doWork return a sensible value. Since Relay and its subclasses are simply ON/OFF switches and the switching occurs in doUpdate, that's probably it.

Analyze, confirm, and implement as appropriate.

**Comment by kyleoliveira** [comment]
Thought about this a little bit, and it is probably appropriate for doWork to do the actual switching on the pin based on what is set in the _state variable (as opposed to doing so in doUpdate upon receipt of an update). In other words, doWork should do something like:

```
  digitalWrite( someWayOfGettingTheSinglePin(), (getState() : HIGH ? LOW) );
```

Still very simple, but doing it in doWork should make for a nice separation of concerns / clean interface.

**Comment by azyth** [comment]
@kyleoliveira So the part of this that gets tricky is with the modulation of the elements with the SSRs and switches.

in come cases we may need to control one element with two pins...pump also(later) one for on off and one for speed/heat level. if we have _pins as a list supplied to us via equipment. whichpins(). we still do not have a way to distinguish which pins are which. do we?

one way around this would be to just use two SSRs and they could be switched in parallel fro both sides of the phase.  but using a switch is usually cheaper but they cannot handle constant switching since they will wear out.

**Comment by kyleoliveira** [comment]
So, there are probably a number of ways to deal with that issue, but the first that come to my mind are:
1) The pins are supplied in an ordered list, so we can simply require that the first pin supplied is the on/off and the second handles the speed
2) Explicitly break whichPins (and probably the pin storage mechanism) into separate variables.

The laziest/easiest is probably to stick with (1).

However, (2) might not be a bad idea... if we did that, we'd probably remove references to "pins" from the Equipment class and handle it in the next level up (Relay and TemperatureSensor). Each of those would need one pin for On/Off. Then the next level up from that (HeatingElement and Pump) wouldn't need anything new (beyond the initial refactoring of Equipment). Finally, when we add support for the next level up from that (variable speed pumps and variable heat elements), those classes would have a variable for the pin to use for handling variability.

Another reason why (2) is kind of a good idea is because of the question of how to handle pin settings for composite Equipment types (Thermostat and RIMS). Really those classes shouldn't care about pins - they're only around to represent a logical grouping of equipment, so including a list of pins is kind of silly (but required at the moment due to the interface defined by Equipment).

**Comment by kyleoliveira** [comment]
Putting a hold label on this until we get #17 sorted out.
